import { Component, OnInit, Input } from '@angular/core';
import { FormGroup, FormBuilder, Validators, FormArray } from '@angular/forms';
import { Participant } from 'src/app/takers/participant.model';
import { NavController } from '@ionic/angular';
import { Router } from '@angular/router';
import { ParticipantsService } from 'src/app/services/participants.service';

@Component({
  selector: 'app-create-edit-participant',
  templateUrl: './create-edit-participant.component.html',
  styleUrls: ['./create-edit-participant.component.scss'],
})
export class CreateEditParticipantComponent implements OnInit {

  form: FormGroup;
  participantName = '';
  participantDescription = '';
  @Input() editParticipant?: Participant;


  constructor(
    private formBuilder: FormBuilder,
    private navCtrl: NavController,
    private router: Router,
    private participantsService: ParticipantsService
  ) { }

  ngOnInit() {

    // If edit mode, prepopulate inputs
    if (this.editParticipant) {
      this.participantName = this.editParticipant.name;
      //this.participantDescription = this.editParticipant.description;
    }

    this.form = this.formBuilder.group({
      name: [this.participantName, Validators.required],
      //description: this.participantDescription
    });

  }

  onSubmit() {

    const newParticipant = new Participant(

      // TODO: id will be created much differently in future - generated by Firebase?
      this.editParticipant ? this.editParticipant.id : Math.floor(Math.random() * 9999).toString(),

      this.form.value.name,
      //this.form.value.description,

    );

    if (this.editParticipant) {
      console.log('TODO: create updateParticipant in participantsService')
      //this.participantsService.updateParticipant(newParticipant);
      this.navCtrl.navigateBack(['/participants']);
    } else {
      this.participantsService.addParticipant(newParticipant);
      this.navCtrl.navigateBack(['/participants']);
    }

    //this.router.navigate(['/takers']);
  }

}
